# Generated by Django 3.1.7 on 2021-04-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210420_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cupom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
